spring:
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: bla_bla_bla
    password: bla_bla_bla
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
    templates:
      path: templates