spring:
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: kotyuha.andriy@chnu.edu.ua
    password: AndriiKot555
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
    templates:
      path: templates