spring:
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: flyway

